### ISSUE TITLE
Minor (esthetic) issue on system status display

### ISSUE THREAD

**Issue by stefanomarty** [fusionpbx/fusionpbx#1641]
I have noticed this minor issue, the CPU Information -> CPU Status text box overruns on the right:

![schermata 2016-06-09 alle 12 04 44](https://cloud.githubusercontent.com/assets/3297621/15926591/297d08d0-2e3d-11e6-8378-bdb5452b7e15.jpg)

![schermata 2016-06-09 alle 12 05 17](https://cloud.githubusercontent.com/assets/3297621/15926628/5a64c0e6-2e3d-11e6-8796-d9a945279e1e.jpg)

Not so important, but probably easy to fix.
SM

**Comment by JoinFreeMe** [comment]
Caused by the output of the $shell_result in /app/system/system.php being not being wrapped

**Comment by kismetgerald** [comment]
I'm on the latest commit - ef787dafbf415f50a24ea718a4adad1dc5ed0a54 - and I don't see this issue anymore.  I believe it has been resolved, please confirm @stefanomarty

**Comment by stefanomarty** [comment]
I've just tried it (I'm on the latest commit as well), but the issue is still there on my system. I'm not a HTML guy, but it looks like it's a wrapping issue (as stated by JoinFreeMe above) inside a < p r e > block.

A quick search pointed me to this:
[https://www.sitepoint.com/everything-need-know-html-pre-element/](url)

Adding this block:
```
        pre {
            white-space: pre-wrap;
        }
```
to /fusionpbx/themes/default/css.php (just below line 1798) made the overflow gone, but ps output in now wrapped (obviously) and less readable. Anyway, I prefer this output to the overruning one.

<img width="1352" alt="schermata 2016-06-26 alle 10 33 26" src="https://cloud.githubusercontent.com/assets/3297621/16361239/a2a8e5fe-3b89-11e6-9aca-1684e7d4afb5.png">

PS: I've not checked if this is impacting on other < p r e > blocks (specifically needing a non-wrapping format).

**Comment by markjcrane** [comment]
Thanks for the suggestion Added to master branch and 4.2 release as a bug fix.
