### ISSUE TITLE
Brand-new install FPBX IVR menus won't play, goes straight to voicemail

### ISSUE THREAD

**Issue by pixel2920** [fusionpbx/fusionpbx#1771]
logs

```
2016-07-22 07:25:38.577065 [ERR] mod_lua.cpp:203 ...xml_handler/resources/scripts/configuration/ivr.conf.lua:48: attempt to concatenate global 'ivr_menu_uuid' (a nil value)
stack traceback:
	...xml_handler/resources/scripts/configuration/ivr.conf.lua:48: in main chunk
	[C]: in function 'dofile'
	/usr/share/freeswitch/scripts/app/xml_handler/index.lua:92: in main chunk
	/usr/share/freeswitch/scripts/app.lua:48: in main chunk
2016-07-22 07:25:38.577065 [ERR] mod_lua.cpp:270 LUA script parse/execute error!
2016-07-22 07:25:38.577065 [ERR] mod_dptools.c:2044 Unable to find menu

2016-07-22 07:25:38.596993 [ERR] mod_lua.cpp:279 No Result
```

**Comment by markjcrane** [comment]
Issue has been confirmed. To work around it save it one more time and it will be corrected. Working on fixing it now.

**Comment by blackc2004** [comment]
I'm having this same symptom, but not the same error message... Here's a posting of my call log
http://pastebin.com/vE2QqeXj


System Information
Version	4.1.0
Git Information	Branch: master 
Commit: c2bbc9e525a31d5e5b249adf564e45cfa38ece5c 
Origin: https://github.com/fusionpbx/fusionpbx 
Project Path	/var/www/fusionpbx
Switch Version	1.6.8 (64bit)

**Comment by pixel2920** [comment]
@blackc2004 That sounds like this issue (#1767) that I experienced a couple of days ago that I was freaking out about in IRC and everyone thought I was crazy

**Comment by blackc2004** [comment]
@pixel2920 you're correct, @DigiDaz gave me that hint, but it's still happening in my LIVE system which is on an older release. I will try to upgrade this weekend and see what happens.

**Comment by blackc2004** [comment]
@pixel2920 you're correct, @DigiDaz gave me that hint, but it's still happening in my LIVE system which is on an older release. I will try to upgrade this weekend and see what happens.

**Comment by pixel2920** [comment]
@blackc2004 You didn't upgrade at all recently?

**Comment by blackc2004** [comment]
Last live update was from June 13th.

**Comment by pixel2920** [comment]
@blackc2004 When was the last time you ran Upgrade > App Defaults?

**Comment by markjcrane** [comment]
IVR Menu should work fine now. You need to update the code to the latest and then re-save the IVR.  There was a problem with the dialplan for the IVR Menu should be working fine now. Tested it several times today.

**Comment by pixel2920** [comment]
Confirmed this is working correctly now.  Created new IVR and works OK.

**Comment by alexb1959** [comment]
I made frequent updates however I am still unable to play a PHRASE on the IVR application.  The fun part is that the exit message plays

**Comment by alexb1959** [comment]
Any idea with that ?  My version is up to date and restarted everytime. HELP would be appreciated
